/**
 * Router — single source of truth. Generated by codegen/assemble.py from pages-manifest.json.
 * Model list routes are wrapped with <SectionTabs> so the top section tab bar appears automatically.
 * Custom routes go in customRoutes and are preserved across regeneration.
 */

import { createBrowserRouter, type RouteObject } from "react-router-dom";

import { AppShell } from "@/layouts/app-shell";
import { RequireAuth } from "@/layouts/require-auth";
import DashboardPage from "@/pages/dashboard";
import GenericModelPage from "@/pages/GenericModelPage";
import LoginPage from "@/pages/login";
import StyleGuidePage from "@/pages/style-guide";


// ── Model page routes (auto-generated region) ──────────────────────
const modelRoutes: RouteObject[] = [

];

// ── Runtime-mode routes (GenericModelPage — renders any model from the schema API) ──
const runtimeRoutes: RouteObject[] = [
  { path: "g/:model", element: <GenericModelPage /> },
  { path: "g/:model/:pk", element: <GenericModelPage /> },
];

// ── Custom routes (manual region — preserved across regeneration) ──
const customRoutes: RouteObject[] = [];

export const router = createBrowserRouter([
  { path: "/login", element: <LoginPage /> },
  {
    path: "/",
    element: (
      <RequireAuth>
        <AppShell />
      </RequireAuth>
    ),
    children: [
      { index: true, element: <DashboardPage /> },
      { path: "style-guide", element: <StyleGuidePage /> },
      ...modelRoutes,
      ...runtimeRoutes,
      ...customRoutes,
      { path: "*", element: <p className="py-20 text-center text-fg-muted">Page not found.</p> },
    ],
  },
]);
