/**
 * Model → section-tabs mapping. Generated by codegen/assemble.py. Consumed by SectionTabs.
 *
 * The example below mirrors codegen/pages-manifest.example.json. The codegen overwrites it from
 * your real manifest. Hand-edit only in pure runtime mode (no codegen).
 */

export interface SectionTab {
  model: string;
  label: string;
  to: string;
}

export interface SectionInfo {
  label: string;
  tabs: SectionTab[];
}

export const sectionForModel: Record<string, SectionInfo> = {
  "blog.Post": {
    label: "Blog",
    tabs: [
      { model: "blog.Post", label: "Posts", to: "/m/blog.Post" },
      { model: "blog.Category", label: "Categories", to: "/m/blog.Category" },
    ],
  },
  "blog.Category": {
    label: "Blog",
    tabs: [
      { model: "blog.Post", label: "Posts", to: "/m/blog.Post" },
      { model: "blog.Category", label: "Categories", to: "/m/blog.Category" },
    ],
  },
};
