/**
 * Model → section-tabs mapping. Generated by codegen/assemble.py. Consumed by SectionTabs.
 */

export interface SectionTab {
  model: string;
  label: string;
  to: string;
}

export interface SectionInfo {
  label: string;
  tabs: SectionTab[];
}

export const sectionForModel: Record<string, SectionInfo> = {

};
