/**
 * Sidebar navigation — single source of truth. Generated by codegen/assemble.py from pages-manifest.json.
 * Each item links to its section's "main model". `members` lists all model paths in the section (for active state).
 */

export interface NavItem {
  label: string;
  to: string;
  members: string[];
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

export const sidebarNav: NavGroup[] = [
  {
    label: "Home",
    items: [{ label: "Dashboard", to: "/", members: ["/"] }],
  },
  {
    label: "System",
    items: [
      { label: "Style guide", to: "/style-guide", members: ["/style-guide"] },
    ],
  },
];
