/**
 * Sidebar navigation — single source of truth. Generated by codegen/assemble.py from pages-manifest.json.
 * Each item links to its section's "main model". `members` lists all model paths in the section (for active state).
 *
 * The example below mirrors codegen/pages-manifest.example.json. When you run the codegen this file is
 * overwritten from your real manifest. Hand-edit it only in pure runtime mode (no codegen).
 */

export interface NavItem {
  label: string;
  to: string;
  members: string[];
}

export interface NavGroup {
  label: string;
  items: NavItem[];
}

export const sidebarNav: NavGroup[] = [
  {
    label: "Home",
    items: [{ label: "Dashboard", to: "/", members: ["/"] }],
  },
  {
    label: "Content",
    items: [{ label: "Blog", to: "/m/blog.Post", members: ["/m/blog.Post", "/m/blog.Category"] }],
  },
  {
    label: "System",
    items: [{ label: "Style guide", to: "/style-guide", members: ["/style-guide"] }],
  },
];
