#!/usr/bin/env python3
"""
pages-manifest.json (section structure) → src/router.tsx + src/layouts/sidebar-nav.ts + src/layouts/sections.ts generator.

Structure: group → section → models[]. The first model of a section is the "main" (one sidebar row);
the rest become top tabs on the main page.
- sidebar: group (bold header) → section (main-model link). Ancillary models are not in the sidebar.
- section-tabs: model → all tabs of the same section. Rendered at the top of the list page.
- router: per-model list/detail routes. The list route is wrapped with <SectionTabs>.

The page directory and detail.tsx presence are inferred from the kebab-cased model name + file existence.
If the directory does not exist the model is skipped with a warning (non-destructive build).
Usage: from the packages/web directory: python3 codegen/assemble.py
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAGES = os.path.join(ROOT, "src", "pages")

# Use pages-manifest.json if present, otherwise fall back to the shipped example.
_manifest_path = os.path.join(HERE, "pages-manifest.json")
if not os.path.isfile(_manifest_path):
    _manifest_path = os.path.join(HERE, "pages-manifest.example.json")
manifest = json.load(open(_manifest_path))


def kebab(model_name: str) -> str:
    """CamelCase model name → kebab dir name (FAQ→faq, PreOrder→pre-order, KospiIndex→kospi-index)."""
    return re.sub(r"(?<=[a-z])(?=[A-Z])", "-", model_name).lower()


def pascal(dir_name: str) -> str:
    return "".join(part.capitalize() for part in dir_name.split("-"))


# ── Flatten the manifest + infer directory/detail ────────────────
sections = []  # {group, label, models:[{model, dir, label, name, has_detail}]}
skipped = []
for group in manifest["groups"]:
    for section in group["sections"]:
        models = []
        for entry in section["models"]:
            model_key = entry["model"]
            model_name = model_key.split(".")[-1]
            page_dir = kebab(model_name)
            abs_dir = os.path.join(PAGES, page_dir)
            if not os.path.isdir(abs_dir):
                skipped.append(model_key)
                continue
            models.append(
                {
                    "model": model_key,
                    "dir": page_dir,
                    "label": entry["label"],
                    "name": pascal(page_dir),
                    "has_detail": os.path.isfile(os.path.join(abs_dir, "detail.tsx")),
                }
            )
        if models:
            sections.append({"group": group["label"], "label": section["label"], "models": models})

all_models = [m for s in sections for m in s["models"]]

# ── router.tsx ─────────────────────────────────────────────────
imports = ['import { SectionTabs } from "@/components/composed/section-tabs";']
routes = []
seen_names = set()
for m in all_models:
    if m["name"] in seen_names:
        continue
    seen_names.add(m["name"])
    imports.append(f'import {m["name"]}ListPage from "@/pages/{m["dir"]}";')
    # The list route is wrapped with SectionTabs (the tab bar only shows when the section has 2+ members — the component decides).
    routes.append(f'  {{ path: "m/{m["model"]}", element: <SectionTabs model="{m["model"]}"><{m["name"]}ListPage /></SectionTabs> }},')
    if m["has_detail"]:
        imports.append(f'import {m["name"]}DetailPage from "@/pages/{m["dir"]}/detail";')
        routes.append(f'  {{ path: "m/{m["model"]}/:pk", element: <{m["name"]}DetailPage /> }},')
    else:
        routes.append(f'  {{ path: "m/{m["model"]}/:pk", element: <{m["name"]}ListPage /> }},')

router = f"""/**
 * Router — single source of truth. Generated by codegen/assemble.py from pages-manifest.json.
 * Model list routes are wrapped with <SectionTabs> so the top section tab bar appears automatically.
 * Custom routes go in customRoutes and are preserved across regeneration.
 */

import {{ createBrowserRouter, type RouteObject }} from "react-router-dom";

import {{ AppShell }} from "@/layouts/app-shell";
import {{ RequireAuth }} from "@/layouts/require-auth";
import DashboardPage from "@/pages/dashboard";
import GenericModelPage from "@/pages/GenericModelPage";
import LoginPage from "@/pages/login";
import StyleGuidePage from "@/pages/style-guide";
{chr(10).join(imports)}

// ── Model page routes (auto-generated region) ──────────────────────
const modelRoutes: RouteObject[] = [
{chr(10).join(routes)}
];

// ── Runtime-mode routes (GenericModelPage — renders any model from the schema API) ──
const runtimeRoutes: RouteObject[] = [
  {{ path: "g/:model", element: <GenericModelPage /> }},
  {{ path: "g/:model/:pk", element: <GenericModelPage /> }},
];

// ── Custom routes (manual region — preserved across regeneration) ──
const customRoutes: RouteObject[] = [];

export const router = createBrowserRouter([
  {{ path: "/login", element: <LoginPage /> }},
  {{
    path: "/",
    element: (
      <RequireAuth>
        <AppShell />
      </RequireAuth>
    ),
    children: [
      {{ index: true, element: <DashboardPage /> }},
      {{ path: "style-guide", element: <StyleGuidePage /> }},
      ...modelRoutes,
      ...runtimeRoutes,
      ...customRoutes,
      {{ path: "*", element: <p className="py-20 text-center text-fg-muted">Page not found.</p> }},
    ],
  }},
]);
"""

# ── sidebar-nav.ts (group → section main model) ──────────────────
groups_order = []
group_sections = {}
for s in sections:
    if s["group"] not in group_sections:
        group_sections[s["group"]] = []
        groups_order.append(s["group"])
    main = s["models"][0]
    members = [m["model"] for m in s["models"]]
    group_sections[s["group"]].append({"label": s["label"], "to": f'/m/{main["model"]}', "members": members})

nav_blocks = ['  {\n    label: "Home",\n    items: [{ label: "Dashboard", to: "/", members: ["/"] }],\n  },']
for group_label in groups_order:
    items = []
    for sec in group_sections[group_label]:
        member_paths = ", ".join(f'"/m/{mk}"' for mk in sec["members"])
        items.append(f'      {{ label: "{sec["label"]}", to: "{sec["to"]}", members: [{member_paths}] }},')
    nav_blocks.append('  {\n    label: "' + group_label + '",\n    items: [\n' + "\n".join(items) + "\n    ],\n  },")
nav_blocks.append('  {\n    label: "System",\n    items: [\n      { label: "Style guide", to: "/style-guide", members: ["/style-guide"] },\n    ],\n  },')

sidebar = f"""/**
 * Sidebar navigation — single source of truth. Generated by codegen/assemble.py from pages-manifest.json.
 * Each item links to its section's "main model". `members` lists all model paths in the section (for active state).
 */

export interface NavItem {{
  label: string;
  to: string;
  members: string[];
}}

export interface NavGroup {{
  label: string;
  items: NavItem[];
}}

export const sidebarNav: NavGroup[] = [
{chr(10).join(nav_blocks)}
];
"""

# ── sections.ts (model → section tab list) ──────────────────────
entries = []
for s in sections:
    tabs = ", ".join(f'{{ model: "{m["model"]}", label: "{m["label"]}", to: "/m/{m["model"]}" }}' for m in s["models"])
    for m in s["models"]:
        entries.append(f'  "{m["model"]}": {{ label: "{s["label"]}", tabs: [{tabs}] }},')

sections_ts = f"""/**
 * Model → section-tabs mapping. Generated by codegen/assemble.py. Consumed by SectionTabs.
 */

export interface SectionTab {{
  model: string;
  label: string;
  to: string;
}}

export interface SectionInfo {{
  label: string;
  tabs: SectionTab[];
}}

export const sectionForModel: Record<string, SectionInfo> = {{
{chr(10).join(entries)}
}};
"""

open(os.path.join(ROOT, "src", "router.tsx"), "w").write(router)
open(os.path.join(ROOT, "src", "layouts", "sidebar-nav.ts"), "w").write(sidebar)
open(os.path.join(ROOT, "src", "layouts", "sections.ts"), "w").write(sections_ts)
print(f"sections: {len(sections)}, models(routes): {len(all_models)}, sidebar groups: {len(groups_order)}, skipped(no dir): {skipped or 'none'}")
